### ISSUE TITLE
Adjust hyperlinks from article to main theme of site

### ISSUE THREAD

**Issue by Kvgelderen** [Portiva-O365/portfolio#2]
It would be great to have the hyperlinks inherit the main theme color from the site. 

In the screenshot you see the hyperlinks from the RSS feed and the bottom is the main theme color. 

![image](https://user-images.githubusercontent.com/45969841/50156080-1af08680-02ce-11e9-9737-0c175af8b2eb.png)

**Comment by Portiva-O365** [comment]
This issue is specific to the RSS web part, Issue moved from here to RSS repository.
